version: "3.9"

services:
  db:
    container_name: chatapp-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./lib/chatapp.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: chat-app
    image: ghcr.io/dinhnq-gihot/axum-chat-app:${VERSION:-latest}
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HOST=0.0.0.0
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./:/opt/app
    command:
      - "/bin/sh"
      - "-c"
      - "/opt/app/start.sh"

  nginx:
    container_name: chatapp-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
